#!/bin/bash  
#PBS -N NavierStokes
#PBS -l walltime=1:00:00
#PBS -l nodes=3:ppn=4  
#PBS -j oe   
#PBS -M changqing.fu@dauphine.eu
# #PBS -m e
# #PBS -e $PBS_JOBNAME$PBS_JOBID.o 
#PBS -e error.txt
# --this prevents permission error
#PBS -o output.txt 

echo "Running on: " 
cat ${PBS_NODEFILE} 

echo 
echo "Program Output begins: " 

cd ${PBS_O_WORKDIR} 

# which ffmpeg
# which python3
python3 ./NS_backflow_server.py
echo
echo $PATH
echo

# ### Quelques infos qui peuvent etre utiles 
# echo Host `hostname`
# echo La liste des CPUs
# hostfile=`cat $PBS_NODEFILE`
# echo $hostfile

# ### Nombre total de CPU
# NPROCS=`wc -l < $PBS_NODEFILE`
# echo Il a ete aloue $NPROCS cpus

# ### Definition de la variable d'env pour OpenMP 
# # $PBS_NUM_PPN est le nombre de CPUs par noeud demande    
# OMP_NUM_THREADS=$PBS_NUM_PPN
# export OMP_NUM_THREADS
# echo Ce job a $OMP_NUM_THREADS cpus