#!/bin/bash                                                                                                                                                                                                                                                                                                                   
#PBS -N TestEnvironment                                                                                                                                                                                                                                                                                                       
#PBS -l walltime=4:00:30                                                                                                                                                                                                                                                                                                      
#PBS -l nodes=1:ppn=8                                                                                                                                                                                                                                                                                                         
#PBS -j oe                                                                                                                                                                                                                                                                                                                    
#PBS -M fuch@ceremade.dauphine.fr                                                                                                                                                                                                                                                                                           
##PBS -m e                                                                                                                                                                                                                                                                                                                    
#PBS -o $PBS_JOBNAME$PBS_JOBID.o                                                                                                                                                                                                                                                                                              

### gestion des repertoires                                                                                                                                                                                                                                                                                                   
echo Repertoire darrivee `pwd`
# repertoire depuis lequel le job a ete soumis                                                                                                                                                                                                                                                                                
echo Repertoire de travail $PBS_O_WORKDIR
# on se déplace dans le répertoire                                                                                                                                                                                                                                                                                            
cd $PBS_O_WORKDIR

### Quelques infos qui peuvent etre utiles                                                                                                                                                                                                                                                                                    
echo Host `hostname`
echo La liste des CPUs
hostfile=`cat $PBS_NODEFILE`
echo $hostfile

### Nombre total de CPU                                                                                                                                                                                                                                                                                                       
NPROCS=`wc -l < $PBS_NODEFILE`
echo Il a ete aloue $NPROCS cpus

### Definition de la variable d'env pour OpenMP                                                                                                                                                                                                                                                                               
# $PBS_NUM_PPN est le nombre de CPUs par noeud demande                                                                                                                                                                                                                                                                        
OMP_NUM_THREADS=$PBS_NUM_PPN
export OMP_NUM_THREADS
echo Ce job a $OMP_NUM_THREADS cpus